vim.opt.number = true                   -- enable line numbers
vim.opt.relativenumber = true           -- use relative line numbers
vim.opt.tabstop = 4                     -- tab is 4 characters long
vim.opt.shiftwidth = 4                  -- standard indenting is 4 spaces
vim.opt.expandtab = true                -- use spaces, not actual tabs
vim.opt.swapfile = false                -- no swapfile
vim.opt.encoding = "utf-8"              -- use utf-8 as standard encoding for compatibility reasons
vim.opt.syntax = "enable"               -- enable syntax highlightning by default
vim.opt.mouse = "v"                     -- use mouse only in visual mode
vim.opt.showmode = false                -- already shown in status line
vim.opt.signcolumn = "yes"              -- always show sign column, prevents the text from shifting with lsp stuff
vim.opt.smartindent = true              -- better indenting
vim.opt.splitbelow = true               -- new vertical splits always below current window
vim.opt.splitright = true               -- new horizontal splits always right of current window
vim.opt.timeoutlen = 1000               -- time (millis) to wait for a mapped sequence to complete
vim.opt.undofile = true                 -- persistent undo
vim.opt.updatetime = 300                -- faster completion
vim.opt.cursorline = true               -- highlight current line
vim.opt.laststatus = 3                  -- only the current window will always have a status line
vim.opt.numberwidth = 4                 -- use 4 columns for line numbers
vim.opt.wrap = false                    -- disable soft line wrap
vim.opt.termguicolors = true            -- set termguicolors to enable highlight groups
